import Navbar from "@/components/NavBar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import BrowserProgess from "@/components/BrowserProgress/BrowserProgess";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Oluwadunsin Olesin | Software Engineer",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
    apple: "./apple-touch-icon.png",
    shortcut: "./favicon-16x16.png",
  },
  manifest: "/public/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
